name: Application Tests
on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "website/**"
      - "*.md"
      - "LICENSE"
      - ".all-contributorsrc"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      UPTIMEROBOT_API_KEY: ${{ secrets.UPTIMEROBOT_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('go.sum') }}

      - name: Setup Code Climate test-reporter
        run: |
          # download test reporter as a static binary
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Build
        run: |
          go build -v

      - name: Run acceptance tests
        run: |
          ./cc-test-reporter before-build
          TF_ACC=1 go test -coverprofile c.out -v ./...
          ./cc-test-reporter after-build --exit-code $? --prefix github.com/${GITHUB_REPOSITORY}/
        env:
          CC_TEST_REPORTER_ID: 52729bbe50d1d3f27774761a3ae11ce34b3a14fbbdfdce903f8736eac52f30c5

      - uses: actions/upload-artifact@v2
        with:
          name: terraform-provider-uptimerobot
          path: /go/bin/terraform-provider-uptimerobot
